# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

source 'https://cdn.cocoapods.org/'
source 'https://github.com/Mapsted/podspec.git'



use_frameworks!

target 'SampleMapUIPOISelection' do
  pod 'mapsted-sdk-map-ui','~> 6.1.11'
  pod 'mapsted-sdk-map','~> 6.1.11'

end

